# ===================================================================
# 正規化マッピング設定
# ===================================================================

# -------------------------------------------------------------------
# 1. 旅行形態 (Traveler Type) - 汎用的なルール
# -------------------------------------------------------------------
traveler_type:
  common:
    家族:
      - 家族
      - 家族旅行
      - ファミリー
      - 小さなお子様連れの家族旅行
      - 大きなお子様連れの家族旅行
    一人:
      - 一人
      - 1人
      - 一人旅
      - 1 人で旅行
    友達:
      - 友達
      - 友だち
      - グループ
      - 友人との旅行
      - 友達旅行
    カップル・夫婦:
      - カップル
      - 夫婦
      - カップル・夫婦
      - カップルで旅行
  ota_specific:
    expedia:
      家族: [家族, 子供連れの家族]
      一人: [同伴者なし]
    rakuten:
      カップル・夫婦: [恋人]
    # ... 他のOTA ...

# -------------------------------------------------------------------
# 2. 旅行目的 (Purpose of Visit) - 派生的なルール
# -------------------------------------------------------------------
purpose_of_visit:
  common:
    ビジネス:
      - ビジネス
      - 出張
      - 出張利用
      - 同僚・仕事関連
      - 出張者
      - 出張・ビジネス
      - ビジネス旅行者
    レジャー:
      - レジャー
      - 休暇
      # --- ここからが派生ルール ---
      # scraper側で「同伴者」が以下のいずれかであれば「レジャー」と判断する
      - 家族
      - ファミリー
      - 友達
      - カップル
      - 恋人
      - 家族旅行
      - 友達旅行
      - 夫婦旅行
      - 友人との旅行
      - カップル・夫婦での旅行
      - 小さなお子様連れの家族旅行
      - 大きなお子様連れの家族旅行
      - グループ旅行者
      - 子供連れの家族

# -------------------------------------------------------------------
# 3. 部屋タイプ (Room Type) - 個別具体的なルール
# -------------------------------------------------------------------
room_type:
  ノボテル奈良: # slugを指定
    rakuten:
      # 正規化後の部屋名: [楽天での表記リスト]
      和洋室:
        - '【和洋室　ツイン　【禁煙/バスタブ】】'
      スタンダードダブル:
        - '【スタンダード　ダブル【禁煙/シャワーブース】】'
      スタンダードツイン:
        - '【スタンダード　ツイン　【禁煙/バスタブ】】'
      エグゼクティブツイン:
        - '【エグゼクティブ　ツイン【バスタブ】ラウンジアクセス付】'
      エグゼクティブダブル:
        - '【エグゼクティブ　ダブル【シャワーブース】ラウンジアクセス付】'
      エグゼクティブ和洋室:
        - '【エグゼクティブ和洋室　ツイン【バスタブ】ラウンジアクセス付】'
    booking_com:
      # 正規化後の部屋名: [Booking.comでの表記リスト]
      スタンダードダブル:
        - 'スタンダード　ダブルルーム　シャワー室付'
      エグゼクティブダブル:
        - 'エグゼクティブ　ダブルルーム　バスタブ付'

  # 他のホテルの設定もここに追加していく
  # a-b-c-hotel:
  #   rakuten:
  #     ...