# ===================================================================
# 正規化マッピング設定
# ===================================================================

# -------------------------------------------------------------------
# 1. 旅行形態 (Traveler Type) - 汎用的なルール
# -------------------------------------------------------------------
traveler_type:
  家族:
    - 家族
    - 家族旅行
    - ファミリー
    - 小さなお子様連れの家族旅行
    - 大きなお子様連れの家族旅行
    - Family
    - 子供連れの家族
  一人:
    - 一人
    - 1人
    - 一人旅
    - 1 人で旅行
    - Solo
    - 同伴者なし
  友達:
    - 友達
    - 友だち
    - グループ
    - 友人との旅行
    - 友達旅行
    - Friends
  カップル・夫婦:
    - カップル
    - 夫婦
    - カップル・夫婦
    - カップルで旅行
    - Couple
    - 夫婦旅行
    - 恋人

# -------------------------------------------------------------------
# 2. 旅行目的 (Purpose of Visit) - 派生的なルール
# -------------------------------------------------------------------
purpose_of_visit:
  ビジネス:
    - ビジネス
    - 出張
    - 出張利用
    - 同僚・仕事関連
    - 出張者
    - 出張・ビジネス
    - ビジネス旅行者
    - Business
  レジャー:
    - レジャー
    - 休暇
    # --- ここからが派生ルール ---
    # scraper側で「同伴者」が以下のいずれかであれば「レジャー」と判断する
    - 家族
    - ファミリー
    - 友達
    - カップル
    - 恋人
    - 家族旅行
    - 友達旅行
    - 夫婦旅行
    - 友人との旅行
    - カップル・夫婦での旅行
    - 小さなお子様連れの家族旅行
    - 大きなお子様連れの家族旅行
    - グループ旅行者
    - 子供連れの家族
    - Holiday
    - 一人旅

# -------------------------------------------------------------------
# 3. 部屋タイプ (Room Type) - 個別具体的なルール
# -------------------------------------------------------------------
room_type:
  ノボテル奈良: # slugを指定
    _common_rooms: &novotel_nara_common_rooms
      和洋室: ['和洋室']
      スタンダードダブル: ['スタンダード　ダブル']
      スタンダードツイン: ['スタンダード　ツイン']
      エグゼクティブツイン: ['エグゼクティブ　ツイン']
      エグゼクティブダブル: ['エグゼクティブ　ダブル']
      エグゼクティブ和洋室: ['エグゼクティブ和洋室']

    rakuten:
      <<: *novotel_nara_common_rooms 
    ikyu:
      <<: *novotel_nara_common_rooms # 共通定義をマージ
    booking_com:
      # 正規化後の部屋名: [Booking.comでの表記リスト]
      スタンダードダブル:
        - 'スタンダード　ダブルルーム'
      エグゼクティブダブル:
        - 'エグゼクティブ　ダブルルーム'

  # 他のホテルの設定もここに追加していく
  # a-b-c-hotel:
  #   rakuten:
  #     ...
