# Generated by Django 3.2.25 on 2025-09-25 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id_in_ota', models.CharField(blank=True, help_text='各OTAサイト内でホテルを一位に識別するID', max_length=50, null=True, verbose_name='OTA内のホテルID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='ホテル名')),
                ('crawl_url', models.URLField(blank=True, help_text='このホテルの口コミ一覧ページのURL', max_length=512, null=True, verbose_name='クロール対象URL')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ホテル（クロール対象）',
                'verbose_name_plural': 'ホテル（クロール対象）',
                'ordering': ['ota', 'hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='Ota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='OTAサイトの名前 (例: Booking.com)', max_length=50, unique=True, verbose_name='OTA名')),
                ('base_url', models.URLField(blank=True, help_text='OTAサイトのトップページのURL', max_length=255, null=True, verbose_name='ベースURL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'OTAサイト',
                'verbose_name_plural': 'OTAサイト',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id_in_ota', models.CharField(blank=True, help_text='取得できる場合のみ格納', max_length=50, null=True, verbose_name='OTA内の口コミID')),
                ('review_hash', models.CharField(db_index=True, editable=False, help_text='レビュー内容から生成された一意のハッシュ値。重複登録の防止に利用。', max_length=64, unique=True, verbose_name='レビューハッシュ')),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='投稿者の表示名')),
                ('nationality_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='国籍（大分類）')),
                ('nationality_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='国籍（小分類）')),
                ('traveler_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='旅行形態')),
                ('purpose_of_visit', models.CharField(blank=True, max_length=50, null=True, verbose_name='旅行の目的')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='性別')),
                ('age_group', models.CharField(blank=True, max_length=20, null=True, verbose_name='年代')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='総合評価点')),
                ('location_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='立地スコア')),
                ('service_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='サービススコア')),
                ('cleanliness_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='清潔感スコア')),
                ('facilities_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='施設スコア')),
                ('food_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='食事スコア')),
                ('price_performance_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='コスパスコア')),
                ('review_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='口コミタイトル')),
                ('review_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='言語')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='口コミ本文')),
                ('location_comment', models.TextField(blank=True, null=True, verbose_name='立地に関するコメント')),
                ('service_comment', models.TextField(blank=True, null=True, verbose_name='サービスに関するコメント')),
                ('cleanliness_comment', models.TextField(blank=True, null=True, verbose_name='清潔感に関するコメント')),
                ('facilities_comment', models.TextField(blank=True, null=True, verbose_name='施設に関するコメント')),
                ('room_comment', models.TextField(blank=True, null=True, verbose_name='客室に関するコメント')),
                ('bath_comment', models.TextField(blank=True, null=True, verbose_name='風呂に関するコメント')),
                ('food_comment', models.TextField(blank=True, null=True, verbose_name='食事全般に関するコメント')),
                ('breakfast_comment', models.TextField(blank=True, null=True, verbose_name='朝食に関するコメント')),
                ('dinner_comment', models.TextField(blank=True, null=True, verbose_name='夕食に関するコメント')),
                ('room_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='部屋タイプ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='予約時の価格。通貨はcurrencyフィールドで指定。', max_digits=10, null=True, verbose_name='価格')),
                ('currency', models.CharField(blank=True, help_text='価格の通貨コード (例: JPY, USD)', max_length=3, null=True, verbose_name='通貨')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='口コミ投稿日')),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ取得日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='データ更新日時')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.hotel', verbose_name='ホテル')),
                ('ota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.ota', verbose_name='OTAサイト')),
            ],
            options={
                'verbose_name': '口コミ情報',
                'verbose_name_plural': '口コミ情報',
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='ota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='reviews.ota', verbose_name='OTAサイト'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('ota', 'hotel_id_in_ota'), name='unique_ota_hotel'),
        ),
    ]
