# Generated by Django 3.2.25 on 2025-10-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stay_date',
            field=models.DateField(blank=True, help_text='口コミ対象の宿泊年月。', null=True, verbose_name='宿泊年月'),
        ),
    ]
