# Generated by Django 3.2.25 on 2025-10-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_stay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, help_text='URLや設定ファイルで使われる、ユニークな識別子。', max_length=100, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='review',
            name='purpose_of_visit_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='旅行の目的（取得元オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='room_type_original',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部屋タイプ（取得元オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='traveler_type_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='旅行形態（取得元オリジナル）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='purpose_of_visit',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='旅行の目的（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='room_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='部屋タイプ（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='traveler_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='旅行形態（正規化済）'),
        ),
    ]
