# Generated by Django 3.2.25 on 2025-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_hotel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='translated_review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='翻訳した口コミ本文'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='オリジナルの口コミ本文'),
        ),
    ]
