# Generated by Django 3.2.25 on 2025-09-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20250926_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ota',
        ),
    ]
