# Generated by Django 3.2.25 on 2025-09-29 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_ota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '処理中'), ('SUCCESS', '成功'), ('FAILURE', '失敗')], default='PENDING', max_length=10, verbose_name='ステータス')),
                ('result_message', models.TextField(blank=True, help_text='成功メッセージやエラー詳細を格納', null=True, verbose_name='結果メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タスク実行ステータス',
                'verbose_name_plural': 'タスク実行ステータス',
                'ordering': ['-created_at'],
            },
        ),
    ]
