# Generated by Django 3.2.25 on 2025-10-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_populate_hotel_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleanliness_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='清潔感スコア（オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='facilities_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='施設スコア（オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='food_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='食事スコア（オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='location_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='立地スコア（オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='original_score_scale',
            field=models.PositiveIntegerField(blank=True, help_text='評価点の満点（例: 5, 10）', null=True, verbose_name='元の評価尺度'),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='総合評価点（取得元オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='price_performance_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='コスパスコア（オリジナル）'),
        ),
        migrations.AddField(
            model_name='review',
            name='service_score_original',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='サービススコア（オリジナル）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='清潔感スコア（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='facilities_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='施設スコア（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='food_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='食事スコア（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='location_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='立地スコア（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True, verbose_name='総合評価点（10点満点に正規化）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='price_performance_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='コスパスコア（正規化済）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='サービススコア（正規化済）'),
        ),
    ]
