# Generated by Django 3.2.25 on 2025-10-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20251011_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='language_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='言語コード'),
        ),
    ]
