# Generated by Django 3.2.25 on 2025-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_taskstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AddField(
            model_name='hotel',
            name='last_crawl_message',
            field=models.TextField(blank=True, help_text='成功メッセージやエラー詳細を格納', null=True, verbose_name='最終クロール結果メッセージ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='last_crawl_status',
            field=models.CharField(choices=[('PENDING', '処理中'), ('SUCCESS', '成功'), ('FAILURE', '失敗'), ('NEVER_RUN', '未実行')], default='NEVER_RUN', help_text='このOTAのホテルの最終クロール結果', max_length=10, verbose_name='最終クロールステータス'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, help_text='最後にクロール処理が実行された日時', null=True, verbose_name='最終クロール日時'),
        ),
    ]
