# Generated by Django 3.2.25 on 2025-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ota',
            options={'ordering': ['display_order', 'pk'], 'verbose_name': 'OTAサイト', 'verbose_name_plural': 'OTAサイト'},
        ),
        migrations.AddField(
            model_name='ota',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='数字が小さい順に表示されます', verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='ota',
            name='is_active',
            field=models.BooleanField(default=True, help_text='チェックを外すとサイトに表示されなくなります', verbose_name='表示フラグ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='言語コード'),
        ),
    ]
