# Generated by Django 3.2.25 on 2025-09-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20250930_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='CrawlTarget',
        ),
    ]
