# Generated by Django 3.2.25 on 2025-10-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20251015_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bath_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='breakfast_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cleanliness_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cleanliness_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cleanliness_score_original',
        ),
        migrations.RemoveField(
            model_name='review',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dinner_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='facilities_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='facilities_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='facilities_score_original',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food_score_original',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location_score_original',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price_performance_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price_performance_score_original',
        ),
        migrations.RemoveField(
            model_name='review',
            name='room_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service_score_original',
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LOCATION', '立地'), ('SERVICE', 'サービス'), ('CLEANLINESS', '清潔感'), ('FACILITIES', '施設'), ('ROOM', '客室'), ('BATH', '風呂'), ('FOOD', '食事')], max_length=20, verbose_name='評価項目')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='スコア（正規化済）')),
                ('score_original', models.CharField(max_length=10, verbose_name='スコア（オリジナル）')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='reviews.review', verbose_name='関連レビュー')),
            ],
            options={
                'verbose_name': '評価スコア詳細',
                'verbose_name_plural': '評価スコア詳細',
                'unique_together': {('review', 'category')},
            },
        ),
    ]
