# Generated by Django 3.2.25 on 2025-10-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20251015_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='nationality_country',
        ),
        migrations.RemoveField(
            model_name='review',
            name='nationality_region',
        ),
    ]
