# Generated by Django 3.2.25 on 2025-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20251016_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawltarget',
            name='hotel_id_in_ota',
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='category',
            field=models.CharField(choices=[('LOCATION', '立地'), ('SERVICE', 'サービス'), ('CLEANLINESS', '清潔感'), ('FACILITIES', '施設'), ('ROOM', '客室'), ('BATH', '風呂'), ('FOOD', '食事'), ('BREAKFAST', '朝食'), ('DINNER', '夕食')], max_length=20, verbose_name='評価項目'),
        ),
    ]
