# Generated by Django 3.2.25 on 2025-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20251024_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltarget',
            name='hotel_id_in_ota',
            field=models.CharField(blank=True, help_text='各OTAサイト内でホテルを一位に識別するID', max_length=50, null=True, verbose_name='OTA内のホテルID'),
        ),
    ]
